FROM ubuntu

ENV PACKAGE openolitor-server
ENV VERSION 2.2.0
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get -y install gnupg vim git wget curl

RUN echo "deb https://dl.bintray.com/sbt/debian /" | tee /etc/apt/sources.list.d/sbt.list && \
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823 && \
    apt-get update && \
    apt-get -y install sbt default-jre

RUN curl -L https://github.com/OpenOlitor/${PACKAGE}/archive/${VERSION}.tar.gz | tar xz && \
    mv ${PACKAGE}-${VERSION} /${PACKAGE}

EXPOSE 9004
EXPOSE 9005

WORKDIR /${PACKAGE}
ENTRYPOINT ["/usr/bin/env", "sbt", "run"]
